### ISSUE TITLE
Album image gets squashed and stretched

### ISSUE THREAD

**Issue by Slushee-a** [lxbx44/time-tunes#14]
Album covers get stretched/squashed depending on how the window is resized

## Current behavior:
![image](https://github.com/lxbx44/time-tunes/assets/55996847/49ccba92-d277-43ce-b744-34fd2ed8d9db)
![image](https://github.com/lxbx44/time-tunes/assets/55996847/a23a9c6a-7762-454c-aaa2-6fd30f744df5)

## Expected behavior:
(Works as expected with the default picture, since it's SVG)
![image](https://github.com/lxbx44/time-tunes/assets/55996847/f7f1e475-242f-4240-aed2-7d2448fe599d)
![image](https://github.com/lxbx44/time-tunes/assets/55996847/da790c15-a364-4bae-bfd1-0a19cf484b5b)

**Comment by Slushee-a** [comment]
Album covers get stretched/squashed depending on how the window is resized

## Current behavior:
![image](https://github.com/lxbx44/time-tunes/assets/55996847/49ccba92-d277-43ce-b744-34fd2ed8d9db)
![image](https://github.com/lxbx44/time-tunes/assets/55996847/a23a9c6a-7762-454c-aaa2-6fd30f744df5)


## Expected behavior:
(Works as expected with the default picture, since it's SVG)
![image](https://github.com/lxbx44/time-tunes/assets/55996847/f7f1e475-242f-4240-aed2-7d2448fe599d)
![image](https://github.com/lxbx44/time-tunes/assets/55996847/da790c15-a364-4bae-bfd1-0a19cf484b5b)

**Comment by lxbx44** [comment]
I guess changing width with max-width and adding aspect ratio to the scss file would fix the issue. I'll take a look later.

**Comment by Slushee-a** [comment]
Any updates?
